version: 0.2

phases:
  install:
    commands:
      - echo installs dependencies
      - npm install @ionic/app-scripts
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - ionic cordova build browser
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - /ionictest/platforms/browser/www
