let Sports = [//@TODO:move to database and API
  "Aikido",
  "Alternative Ice Hockey",
  "Boxing",
  "American Football",
  "Archery",
  "Athletics",
  "Australian Rules Football",
  "Badminton",
  "Baseball and Softball",
  "Basketball",
  "Rowing",
  "Kayaking, Canoeing",
  "Caving",
  "Cheerleading",
  "Clay pigeon Shooting",
  "Contemporay Dance",
  "Cricket",
  "Croquet",
  "Cross Country",
  "Cycling",
  "Dancesport",
  "Equestrian",
  "Eton Fives",
  "Fencing",
  "Floorball",
  "Football",
  "Gliding",
  "Golf",
  "Gymnastics",
  "Handball",
  "Hockey",
  "Ice Hockey",
  "Jiu Jitsu",
  "Judo",
  "Kabaddi",
  "Karate",
  "Karate-Do Shotokai",
  "Kendo",
  "Kickboxing",
  "Korfball",
  "K.O. Krav",
  "Lacrosse",
  "Lawn Tennis",
  "Lifesaving",
  "Pentathlon",
  "Motor Sport",
  "Mountaineering",
  "Netball",
  "Octopush",
  "Orienteering",
  "Pistol",
  "Polo",
  "Pool and Snooker",
  "Powerlifting",
  "Rackets",
  "Real Tennis",
  "Rifle",
  "Rugby Fives",
  "Rugby League",
  "Rugby Union",
  "Shorinji Kempo",
  "Ski, Snowboard",
  "Squash",
  "Sulkido",
  "Surfing",
  "Swimming",
  "Table Tennis",
  "TaeKwon Do",
  "Tai Chi",
  "Trampolining",
  "Triathlon",
  "Ultimate",
  "Underwater Exploration",
  "Volleyball",
  "Walking",
  "Waterpolo",
  "Windsurfing",
  "Yachting",
  "Other",
];

export {Sports};
