version: 0.2

phases:
  install:
    commands:
      - echo installs dependencies
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - apt-get upgrade -y
      - pwd
      - ll
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
   - ${CODEBUILD_SRC_DIR}/platforms/android/build/outputs/apk/debug/*.apk
  discard-paths: yes
  name: android-$(date +%Y-%m-%d)
